
:root{--bg:#f7f2ec;--card:#fff;--soft:#efe4d7;--text:#27272a;--muted:#6b7280;--accent:#8b6a42;--dark:#1d1a17;--line:rgba(0,0,0,.08)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--text);font-family:Arial,Helvetica,sans-serif}a{color:inherit;text-decoration:none}button{font:inherit}
.container{max-width:1180px;margin:0 auto;padding:0 24px}.nav{position:sticky;top:0;z-index:50;background:rgba(247,242,236,.94);backdrop-filter:blur(10px);border-bottom:1px solid rgba(0,0,0,.05)}
.nav-inner{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:18px 0}.brand{font-size:22px;font-weight:700}.subbrand{margin-top:4px;font-size:11px;text-transform:uppercase;letter-spacing:.24em;color:var(--muted)}
.nav-links{display:flex;gap:18px;flex-wrap:wrap;font-size:14px}.lang-switch{display:flex;gap:8px}.lang-btn{border:0;border-radius:999px;padding:8px 12px;cursor:pointer;background:#fff;color:var(--text)}.lang-btn.active{background:#111;color:#fff}
.hero{display:grid;grid-template-columns:1.1fr .9fr;gap:38px;align-items:center;padding:72px 0}.pill{display:inline-block;border:1px solid rgba(139,106,66,.28);background:rgba(255,255,255,.8);border-radius:999px;padding:10px 16px;font-size:11px;text-transform:uppercase;letter-spacing:.22em;color:#4b5563}
h1,h2,h3{font-family:Georgia,"Times New Roman",serif;font-weight:400}.hero h1{font-size:58px;line-height:1.08;margin:18px 0 0;max-width:680px}.lead{color:var(--muted);font-size:18px;line-height:1.8;max-width:640px}
.btn-row{display:flex;gap:14px;flex-wrap:wrap;margin-top:28px}.btn{display:inline-block;border-radius:18px;padding:14px 22px;font-weight:700;border:1px solid #111;background:#111;color:#fff}.btn.secondary{background:transparent;color:#111}
.info-grid{margin-top:28px;display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.info-box,.card,.contact-card{background:#fff;border-radius:24px;box-shadow:0 8px 24px rgba(0,0,0,.05)}.info-box{padding:18px;font-size:14px;font-weight:600}
.hero-panel{border-radius:32px;padding:24px;background:linear-gradient(135deg,#fff 0%,#efe4d7 100%);border:1px solid rgba(139,106,66,.18);box-shadow:0 18px 40px rgba(0,0,0,.08)}.hero-panel-inner{background:#fcfaf7;border-radius:24px;padding:28px}
.section{padding:84px 0}.section.alt{background:rgba(255,255,255,.72)}.section-head{max-width:760px;margin:0 auto 42px;text-align:center}.kicker{font-size:11px;letter-spacing:.25em;text-transform:uppercase;color:var(--muted);margin-bottom:8px}.section h2{font-size:44px;margin:0}.section-copy{font-size:17px;line-height:1.8;color:var(--muted)}
.treatments-layout{display:grid;grid-template-columns:1.1fr .9fr;gap:28px}.treatments-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.treatment-card{border:1px solid rgba(255,255,255,.7);border-radius:24px;padding:22px;text-align:left;cursor:pointer;background:rgba(255,255,255,.78)}.treatment-card.active{background:#fff;border-color:rgba(139,106,66,.7);box-shadow:0 8px 22px rgba(0,0,0,.04)}
.tag{display:inline-block;border-radius:999px;padding:7px 11px;background:var(--soft);color:#7b5c37;font-size:12px}.price{color:var(--accent);font-weight:700;font-size:14px}.detail-card{position:sticky;top:92px;padding:28px}.detail-card p,.package-card p,.shop-card p,.blog-card p,.about-copy p,.contact-copy p{color:var(--muted);line-height:1.8}
.packages-grid,.shop-grid,.blog-grid,.trust-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.package-card,.shop-card,.blog-card{padding:24px}.shop-visual{height:150px;border-radius:20px;background:var(--soft);display:flex;align-items:center;justify-content:center;font-size:42px}
.about-copy{max-width:900px;margin:0 auto;text-align:center}.trust-box{padding:20px;text-align:center}.booking{background:var(--dark);color:#fff}.booking .section-copy{color:rgba(255,255,255,.74)}.booking-chip{display:inline-block;margin-top:22px;border:1px solid rgba(255,255,255,.12);border-radius:999px;padding:10px 14px;color:rgba(255,255,255,.72);font-size:14px}
.contact-layout{display:grid;grid-template-columns:.9fr 1.1fr;gap:28px}.contact-card{padding:24px}.form-grid{display:grid;gap:14px}.input,.textarea{width:100%;border:1px solid var(--line);border-radius:16px;padding:14px 16px;font:inherit;background:#fff}.textarea{min-height:140px;resize:vertical}
.footer{border-top:1px solid rgba(0,0,0,.06);padding:28px 0}.footer-inner{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.footer-links{display:flex;flex-wrap:wrap;gap:18px;color:var(--muted)}.small-note{font-size:14px}
@media (max-width:960px){.nav-links{display:none}.hero,.treatments-layout,.contact-layout{grid-template-columns:1fr}.info-grid,.treatments-grid,.packages-grid,.shop-grid,.blog-grid,.trust-grid{grid-template-columns:1fr}.hero h1{font-size:42px}.section h2{font-size:34px}.detail-card{position:static}}
